### ISSUE TITLE
build_identifier should take id

### ISSUE THREAD

**Issue by shuhaowu** [gbin/err-backend-discord#15]
Sending messages to a room with multiple servers could be confusing without using id or server name.

In fact, sending to anyone specific would be more convenient with the ID that discord gives you.

**Comment by Djiit** [comment]
Hi there,

Do you have a concrete use case ? I'm not sure to get the point of sending a message to a room with multiple servers. Do you mean a server with multiple rooms ?

**Comment by shuhaowu** [comment]
If your bot is in multiple servers and they have rooms with the same name, such as `#general`.

`build_identifier("#general")` is ambiguous afaict.

**Comment by nzlosh** [comment]
Feature added in #45
