### ISSUE TITLE
DiscordBackend.on_ready should send a callback of some sort

### ISSUE THREAD

**Issue by shuhaowu** [gbin/err-backend-discord#16]
Not sure if this goes with the Errbot spec, but it would be nice to send a callback for when the bot joined all the channels. Otherwise sending a message to some channel/person might result in a silent failure.

**Comment by shuhaowu** [comment]
I did a change to https://github.com/shuhaowu/err-backend-discord/commit/43fcb411c5850a5c8adeb7fc9772e72a2dd51572, but don't have the time to put a proper PR at the moment.

**Comment by Djiit** [comment]
For the Errbot spec part, I leave it to @gbin.
When you do have some time, i'll be happy to review your PR. Thanks !

**Comment by nzlosh** [comment]
This has been fixed in commit https://github.com/gbin/err-backend-discord/commit/9d6e30d6c860d434fdb4574f4f71f8c3ac82f1b2
