### ISSUE TITLE
API Changes - Backend Broken

### ISSUE THREAD

**Issue by lcizzle** [gbin/err-backend-discord#19]
Looks like errbot has changed quiet a bit since the last update of the backend. Any chance we can get it looked at? My python chops are good enough yet to maintain it.

For example.

from errbot.errBot import ErrBot (Doesn't exist anymore)
from errbot.core import ErrBot (New)

**Comment by nzlosh** [comment]
@icizzle A new branch `development` has been created where active development will occur to get the discord backend up to date.  Once the backend is functional, it will be merged to master.
