### ISSUE TITLE
Require mainainer?

### ISSUE THREAD

**Issue by nzlosh** [gbin/err-backend-discord#20]
What's the status of this repository?

I saw that @Josh-00FF00 is actively patching a fork.  @Josh-00FF00 Are you planning to push upstream?

**Comment by Josh-00FF00** [comment]
I'd be happy to, although it's quite hacked together currently and quite a large rewrite to get the new discord API working. I'll clean it up some and submit a pull request sometime soon (tm)

**Comment by nzlosh** [comment]
I'd also like to contribute.  I've merged most of your changes into my own repo so I can apply fixes as I encounter issues.  If we were able to collaborate via the official repo that would be ideal.  @gbin what's required to become a collaborator for this repo?

**Comment by gbin** [comment]
Np I put you maintainer of the project on the official repo.

**Comment by gbin** [comment]
We can also move it to errbot io too?

**Comment by Josh-00FF00** [comment]
>We can also move it to errbot io too?

Not sure I follow, you mean the main errbot repo at https://github.com/errbotio/errbot ?

**Comment by gbin** [comment]
I mean moving this repo to the errbotio org :)

**Comment by nzlosh** [comment]
Thank you very much @gbin.  I'd be fine with moving it to errbot io, but would this make the backend part of the core backends deployed?  If it's the case, it would be best to wait until we've got unit tests and a fully functional backend.

**Comment by nzlosh** [comment]
@Josh-00FF00 would you mind merging your fork into a `development` branch on this repo so we can start working together to update the backend?

**Comment by Josh-00FF00** [comment]
Don't seem to have write access to create branches here, could you create the develop branch and I'll submit a pull request?

**Comment by nzlosh** [comment]
OK, I've setup a development branch that we can work in.  https://github.com/gbin/err-backend-discord/tree/development

**Comment by nzlosh** [comment]
@Josh-00FF00 are you on the errbot gitter channel?  It would be good to be able to exchange via instant message.

**Comment by Josh-00FF00** [comment]
Just joined @nzlosh

**Comment by nzlosh** [comment]
Great! I'll close this issue and we can discuss things via gitter
