### ISSUE TITLE
Known Issues?

### ISSUE THREAD

**Issue by btotharye** [gbin/err-backend-discord#5]
There any known issues with this repo?  I"m going to look through the code but when initially setting up the bot is online but when I send !help through to it I'm getting the following:

```
14:12:11 ERROR    errbot.core               An error happened while processing a message ("!help"): Traceback (most recentcall last):
  File "/usr/local/lib/python3.5/dist-packages/errbot/core.py", line 461, in _execute_and_send
    self.send_simple_reply(msg, self.process_template(template_name, reply), private, threaded)
  File "/usr/local/lib/python3.5/dist-packages/errbot/core.py", line 198, in send_simple_reply
    reply = self.build_reply(msg, text, private=private, threaded=threaded)
TypeError: build_reply() got an unexpected keyword argument 'threaded'
"
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/errbot/core.py", line 461, in _execute_and_send
    self.send_simple_reply(msg, self.process_template(template_name, reply), private, threaded)
  File "/usr/local/lib/python3.5/dist-packages/errbot/core.py", line 198, in send_simple_reply
    reply = self.build_reply(msg, text, private=private, threaded=threaded)
TypeError: build_reply() got an unexpected keyword argument 'threaded'

```

**Comment by gbin** [comment]
Ha it needs to be updated for errbot 5.x. If you are game for a PR, this is just the new contract for threaded responses, maybe first add the parameter and ignore it so it runs then maybe implement it if discord supports it.

**Comment by btotharye** [comment]
Yea I just see what it was as well I'm updating it now

**Comment by btotharye** [comment]
do you have an example of how this should look by chance from another backend?

**Comment by btotharye** [comment]
https://github.com/btotharye/err-backend-discord/tree/fix_threading seems to be working atm btw

**Comment by btotharye** [comment]
also how should the formatting be for the bot admin on this?  So far the username or number of the username doesn't seem to be working that I'm getting from the logs.

**Comment by btotharye** [comment]
nvm looks like its some really long unique ID you have to use from the logs

**Comment by btotharye** [comment]
ok all good and working 

![image](https://user-images.githubusercontent.com/1426587/30249976-0a476d7a-9615-11e7-987f-6aa5f47408d6.png)
