### ISSUE TITLE
Can´t find Discord plugin

### ISSUE THREAD

**Issue by futex** [gbin/err-backend-discord#57]
Hello,

I have installed discord plugin in my python ven
`pip3 list | grep -i err 
err-backend-discord     4.0.0
errbot                  6.1.9
discord.py              2.0.1
`
And configure the config.py as expected after the errbot --init
`BACKEND = "Discord"`

But when i start errbot it didn't find the discord plugin
`errbot.backend_plugin_manager.PluginNotFoundException: Could not find the plugin named Discord in ....`

**Comment by futex** [comment]
I found the solution, it miss one thing in the tutorial : https://err-backend-discord.readthedocs.io/en/master/configuration.html
In the config.py you should add this line: 
`BOT_EXTRA_BACKEND_DIR = '/path_to/err-backend-discord'`

A semi colon is also missing at initial_intents end of line
`BOT_IDENTITY = {
    "token": "<bot_token>",
    "initial_intents": "<initial_intent_state>"
    "intents": []
}`

**Comment by nzlosh** [comment]
Good to see the documentation got you moving forward.  A fix to find plugins installed via pip was added to errbot `master` but it hasn't been released as yet, so `BOT_EXTRA_BACKEND_DIR` shouldn't be necessary with the next release of errbot.
