### ISSUE TITLE
On Join Hello

### ISSUE THREAD

**Issue by btotharye** [gbin/err-backend-discord#9]
Is this a concept I should build into errbot or the backend?  I would like for the bot on user join events to msg them hello and maybe a canned response, was going to look at adding it into discord first since its what I use most.

let me know your thoughts

**Comment by gbin** [comment]
There is an Errbot API for that and it works on most of the other backends. It is called Presence. See how it is implemented on the Slack backend here: https://github.com/errbotio/errbot/blob/master/errbot/backends/slack.py#L424

**Comment by gbin** [comment]
Utlimately it calls back the plugins through https://github.com/errbotio/errbot/blob/master/errbot/botplugin.py#L435

**Comment by btotharye** [comment]
Ok cool I'll work on this some today thanks again really loving errbot

**Comment by nzlosh** [comment]
Closing this issue.  Re-open it if you feel there is anything still outstanding.
